version: "3.3"
services:
  db:
    container_name: dc-db
    restart: always
    image: dc-db
    build:
      context: ./packages/db
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./prod.env
    networks:
      - network
    ports:
      - 5433:5432
  server:
    container_name: dc-server
    restart: always
    image: dc-server
    build:
      context: ./packages/server
    env_file:
      - ./prod.env
    depends_on:
      - db
    networks:
      - network
    ports:
      - 5434:5434
  app:
    container_name: dc-app
    restart: always
    image: dc-app
    build:
      context: ./packages/app
    depends_on:
      - server
    networks:
      - network
    ports:
      - 8080:80

networks:
  network:

volumes:
  db:
