runtime: nodejs14

manual_scaling:
  instances: 1
resources:
  cpu: .5
  memory_gb: .5
  disk_size_gb: 10

handlers:
  - url: /graphql
    script: auto

  - url: /(.*\..+)$
    static_files: build/\1
    upload: build/(.*\..+)$

  - url: /.*
    static_files: build/index.html
    upload: build/index.html
