BEGIN;
GRANT CONNECT ON DATABASE :DATABASE_NAME TO :DATABASE_OWNER;
GRANT CONNECT ON DATABASE :DATABASE_NAME TO :DATABASE_AUTHENTICATOR;
GRANT ALL ON DATABASE :DATABASE_NAME TO :DATABASE_OWNER;
ALTER SCHEMA public OWNER TO :DATABASE_OWNER;

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;
CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;
CREATE EXTENSION IF NOT EXISTS mysql_fdw WITH SCHEMA public;

CREATE SERVER legacy_stats_mysql FOREIGN DATA WRAPPER mysql_fdw OPTIONS (host ':LEGACY_DB_HOST', port '3306');
CREATE USER MAPPING FOR PUBLIC SERVER legacy_stats_mysql OPTIONS (username ':LEGACY_DB_USER', password ':LEGACY_DB_PASS');
COMMIT;
