export const players = [
  'Sam Myers',
  'Steven Chan',
  'Cameron Walls',
  'Carlos Ortega',
  'Yukhi Yamashita',
  'James Lockwood',
  'Matthew Chinn',
  'Santiago Aspinal',
  'Jason Tong',
  'Jessie Hinojosa',
  'Andrew Silva',
  'Quincy Zhao',
  'Lowel Knapp',
  'Luis Rodriguez',
  'Dale Zelmon',
  'Mike Basta',
  'Jimmy Dias',
  'Paul Herman',
];
